Task 1

Load and inspect the dataset

In [1]:
import pandas as pd

df = pd.read_csv("insurance_policy_renewal_dataset.xls")
df.head()

,Customer_ID,Age,Policy_Type,Annual_Premium,Years_With_Company,Number_of_Claims,Claim_Amount_Last_Year,Payment_Method,Customer_Service_Calls,Satisfaction_Score,Received_Discount,Auto_Renew_Enabled,Renewed_Policy
0,1,29.0,Auto,3250.0,9,4,1006,Credit Card,1,3.0,No,Yes,Yes
1,2,48.0,Health,2514.0,10,4,5228,Credit Card,10,2.0,No,No,No
2,3,41.0,Life,4760.0,3,2,13296,Credit Card,3,2.0,No,Yes,No
3,4,56.0,Auto,5849.0,4,3,11569,Bank Transfer,4,1.0,No,NaN,No
4,5,71.0,Health,4589.0,12,0,8274,Bank Transfer,5,4.0,No,Yes,Yes

In [2]:
# Show general information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 346 entries, 0 to 345
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer_ID             346 non-null    int64
 1   Age                     338 non-null    float64
 2   Policy_Type             340 non-null    object
 3   Annual_Premium          340 non-null    float64
 4   Years_With_Company      346 non-null    int64
 5   Number_of_Claims        346 non-null    int64
 6   Claim_Amount_Last_Year  346 non-null    int64
 7   Payment_Method          339 non-null    object
 8   Customer_Service_Calls  346 non-null    int64
 9   Satisfaction_Score      340 non-null    float64
 10  Received_Discount       346 non-null    object
 11  Auto_Renew_Enabled      340 non-null    object
 12  Renewed_Policy          346 non-null    object
dtypes: float64(3), int64(5), object(5)
memory usage: 35.3+ KB

In [3]:
# Understand the business problem

# Business problem:
business_problem = "A company wants to predict which customers are likely to renew their insurance policy."

# Machine learning problem:
ml_problem = "This is a classification problem because we want to predict whether the customer will renew or not."

# Prediction goal:
prediction_goal = "Predict whether a customer will renew an insurance policy: Yes or No."

# Display the problem definition
print("Business Problem:")
print(business_problem)

print("\nMachine Learning Problem:")
print(ml_problem)

print("\nPrediction Goal:")
print(prediction_goal)

Business Problem:
A company wants to predict which customers are likely to renew their insurance policy.

Machine Learning Problem:
This is a classification problem because we want to predict whether the customer will renew or not.

Prediction Goal:
Predict whether a customer will renew an insurance policy: Yes or No.

In [4]:
# Identify the features and target variable
# Define x and y

# Define the feature columns
feature_columns = [
    "Age",
    "Policy_Type",
    "Annual_Premium",
    "Years_With_Company",
    "Number_of_Claims",
    "Claim_Amount_Last_Year",
    "Payment_Method",
    "Customer_Service_Calls",
    "Satisfaction_Score",
    "Received_Discount",
    "Auto_Renew_Enabled"
]

# Define X as the feature matrix
X = df[feature_columns]

# Define y as the target variable
y = df["Renewed_Policy"]

# Display the first 5 rows of X
print("Features (X):")
display(X.head())

# Display the first 5 values of y
print("Target (y):")
display(y.head())

Features (X):

,Age,Policy_Type,Annual_Premium,Years_With_Company,Number_of_Claims,Claim_Amount_Last_Year,Payment_Method,Customer_Service_Calls,Satisfaction_Score,Received_Discount,Auto_Renew_Enabled
0,29.0,Auto,3250.0,9,4,1006,Credit Card,1,3.0,No,Yes
1,48.0,Health,2514.0,10,4,5228,Credit Card,10,2.0,No,No
2,41.0,Life,4760.0,3,2,13296,Credit Card,3,2.0,No,Yes
3,56.0,Auto,5849.0,4,3,11569,Bank Transfer,4,1.0,No,NaN
4,71.0,Health,4589.0,12,0,8274,Bank Transfer,5,4.0,No,Yes

Target (y):

0    Yes
1     No
2     No
3     No
4    Yes
Name: Renewed_Policy, dtype: object

In [5]:
# Check the shape of X and y

# X should have rows and feature columns
print("Shape of X:", X.shape)

# y should have only rows
print("Shape of y:", y.shape)

Shape of X: (346, 11)
Shape of y: (346,)

Clean the data

In [6]:
# Create a copy of the original dataset before cleaning
df_clean = df.copy()

# Display the number of missing values in each column
print("Missing values before cleaning:")
print(df_clean.isnull().sum())

# Display the number of duplicate rows in the dataset
print("\nNumber of duplicate rows before cleaning:")
print(df_clean.duplicated().sum())

# Display the data type of each column
print("\nData types before cleaning:")
print(df_clean.dtypes)

Missing values before cleaning:
Customer_ID               0
Age                       8
Policy_Type               6
Annual_Premium            6
Years_With_Company        0
Number_of_Claims          0
Claim_Amount_Last_Year    0
Payment_Method            7
Customer_Service_Calls    0
Satisfaction_Score        6
Received_Discount         0
Auto_Renew_Enabled        6
Renewed_Policy            0
dtype: int64

Number of duplicate rows before cleaning:
6

Data types before cleaning:
Customer_ID                 int64
Age                       float64
Policy_Type                object
Annual_Premium            float64
Years_With_Company          int64
Number_of_Claims            int64
Claim_Amount_Last_Year      int64
Payment_Method             object
Customer_Service_Calls      int64
Satisfaction_Score        float64
Received_Discount          object
Auto_Renew_Enabled         object
Renewed_Policy             object
dtype: object

In [7]:
# Handle missing values

# Fill numerical missing values with the median value
numerical_columns_to_fill = ["Age", "Annual_Premium", "Satisfaction_Score"]
for col in numerical_columns_to_fill:
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())

# Fill categorical missing values with the most frequent value using mode()[0]
categorical_columns_to_fill = ["Policy_Type", "Payment_Method", "Auto_Renew_Enabled"]
for col in categorical_columns_to_fill:
    df_clean[col] = df_clean[col].fillna(df_clean[col].mode()[0])
    
# Remove duplicate rows from the dataset
df_clean = df_clean.drop_duplicates()

# Display the dataset after removing duplicates
df_clean.head()

,Customer_ID,Age,Policy_Type,Annual_Premium,Years_With_Company,Number_of_Claims,Claim_Amount_Last_Year,Payment_Method,Customer_Service_Calls,Satisfaction_Score,Received_Discount,Auto_Renew_Enabled,Renewed_Policy
0,1,29.0,Auto,3250.0,9,4,1006,Credit Card,1,3.0,No,Yes,Yes
1,2,48.0,Health,2514.0,10,4,5228,Credit Card,10,2.0,No,No,No
2,3,41.0,Life,4760.0,3,2,13296,Credit Card,3,2.0,No,Yes,No
3,4,56.0,Auto,5849.0,4,3,11569,Bank Transfer,4,1.0,No,Yes,No
4,5,71.0,Health,4589.0,12,0,8274,Bank Transfer,5,4.0,No,Yes,Yes

In [8]:
# Convert Customer_ID, Age, Years_With_Company, Number_of_Claims, Customer_Service_Calls and Satisfaction_Score variables to integer
int_columns = [
    "Customer_ID",
    "Age",
    "Years_With_Company",
    "Number_of_Claims",
    "Customer_Service_Calls",
    "Satisfaction_Score"
]
df_clean[int_columns] = df_clean[int_columns].astype(int)

# Convert Annual_Premium and Claim_Amount_Last_Year variables to float since it may contain decimal points after cleaning
float_columns = [
    "Annual_Premium",
    "Claim_Amount_Last_Year"
]
df_clean[float_columns] = df_clean[float_columns].astype(float)

# Convert categorical columns to category type
categorical_columns = [
    "Policy_Type",
    "Payment_Method",
    "Received_Discount",
    "Auto_Renew_Enabled",
    "Renewed_Policy"
]
df_clean[categorical_columns] = df_clean[categorical_columns].astype("category")

# Display data types after cleaning
print("Data types after cleaning:")
print(df_clean.dtypes)

Data types after cleaning:
Customer_ID                  int64
Age                          int64
Policy_Type               category
Annual_Premium             float64
Years_With_Company           int64
Number_of_Claims             int64
Claim_Amount_Last_Year     float64
Payment_Method            category
Customer_Service_Calls       int64
Satisfaction_Score           int64
Received_Discount         category
Auto_Renew_Enabled        category
Renewed_Policy            category
dtype: object

In [9]:
# Inspect data again after cleaning

# Check missing values
print("Missing values after cleaning:")
print(df_clean.isnull().sum())

# Check duplicate rows
print("\nNumber of duplicate rows after cleaning:")
print(df_clean.duplicated().sum())

# Display the shape of the cleaned dataset
print("\nShape of cleaned dataset:")
print(df_clean.shape)

# Display the first 5 rows of the cleaned dataset
df_clean.head()

Missing values after cleaning:
Customer_ID               0
Age                       0
Policy_Type               0
Annual_Premium            0
Years_With_Company        0
Number_of_Claims          0
Claim_Amount_Last_Year    0
Payment_Method            0
Customer_Service_Calls    0
Satisfaction_Score        0
Received_Discount         0
Auto_Renew_Enabled        0
Renewed_Policy            0
dtype: int64

Number of duplicate rows after cleaning:
0

Shape of cleaned dataset:
(340, 13)

,Customer_ID,Age,Policy_Type,Annual_Premium,Years_With_Company,Number_of_Claims,Claim_Amount_Last_Year,Payment_Method,Customer_Service_Calls,Satisfaction_Score,Received_Discount,Auto_Renew_Enabled,Renewed_Policy
0,1,29,Auto,3250.0,9,4,1006.0,Credit Card,1,3,No,Yes,Yes
1,2,48,Health,2514.0,10,4,5228.0,Credit Card,10,2,No,No,No
2,3,41,Life,4760.0,3,2,13296.0,Credit Card,3,2,No,Yes,No
3,4,56,Auto,5849.0,4,3,11569.0,Bank Transfer,4,1,No,Yes,No
4,5,71,Health,4589.0,12,0,8274.0,Bank Transfer,5,4,No,Yes,Yes

Preprocessing: Handling categorical and numerical variables

In [10]:
# Import ColumnTransformer to apply different preprocessing steps to different columns
from sklearn.compose import ColumnTransformer

# Import OneHotEncoder for categorical variables
# Import StandardScaler for numerical variables
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [11]:
# Define the feature columns
# These are the input variables that the model will use
feature_columns = [
    "Age",
    "Policy_Type",
    "Annual_Premium",
    "Years_With_Company",
    "Number_of_Claims",
    "Claim_Amount_Last_Year",
    "Payment_Method",
    "Customer_Service_Calls",
    "Satisfaction_Score",
    "Received_Discount",
    "Auto_Renew_Enabled"
]

# Define X as the feature matrix
X = df_clean[feature_columns]

# Define y as the target variable
y = df_clean["Renewed_Policy"]

In [12]:
# Convert the target variable from text labels to numbers
# "No" becomes 0 and "Yes" becomes 1
y = y.map({"No": 0, "Yes": 1})

In [13]:
# Define numerical features
# These columns contain numbers and will be scaled
numerical_features = [
    "Age",
    "Annual_Premium",
    "Years_With_Company",
    "Number_of_Claims",
    "Claim_Amount_Last_Year",
    "Customer_Service_Calls",
    "Satisfaction_Score",
]

In [14]:
# Define categorical features
# These columns contain text categories and will be encoded
categorical_features = [
    "Policy_Type",
    "Payment_Method",
    "Received_Discount",
    "Auto_Renew_Enabled"
]

In [15]:
# Create a preprocessing object
# StandardScaler will be applied to numerical columns
# OneHotEncoder will be applied to categorical columns
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

In [16]:
print("Features before preprocessing:")

display(X.head())
display(y.head())

Features before preprocessing:

,Age,Policy_Type,Annual_Premium,Years_With_Company,Number_of_Claims,Claim_Amount_Last_Year,Payment_Method,Customer_Service_Calls,Satisfaction_Score,Received_Discount,Auto_Renew_Enabled
0,29,Auto,3250.0,9,4,1006.0,Credit Card,1,3,No,Yes
1,48,Health,2514.0,10,4,5228.0,Credit Card,10,2,No,No
2,41,Life,4760.0,3,2,13296.0,Credit Card,3,2,No,Yes
3,56,Auto,5849.0,4,3,11569.0,Bank Transfer,4,1,No,Yes
4,71,Health,4589.0,12,0,8274.0,Bank Transfer,5,4,No,Yes

0    1
1    0
2    0
3    0
4    1
Name: Renewed_Policy, dtype: category
Categories (2, int64): [0, 1]

Preprocessing: Split the data into training and testing

In [17]:
# Import train_test_split from scikit-learn
from sklearn.model_selection import train_test_split
# Split X and y into training and testing sets
# test_size=0.2 means 20% of the data will be used for testing
# random_state=42 makes the result reproducible
# stratify=y keeps the same class distribution in training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [18]:
# Display the shape of the training and testing sets

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (272, 11)
X_test shape: (68, 11)
y_train shape: (272,)
y_test shape: (68,)

In [19]:
# Display the first 5 rows of the training features

print("Training features:")
display(X_train.head())

# Display the first 5 rows of the testing features

print("Testing features:")
display(X_test.head())

Training features:

,Age,Policy_Type,Annual_Premium,Years_With_Company,Number_of_Claims,Claim_Amount_Last_Year,Payment_Method,Customer_Service_Calls,Satisfaction_Score,Received_Discount,Auto_Renew_Enabled
177,43,Life,2995.5,3,1,8326.0,Bank Transfer,5,2,Yes,No
339,65,Home,1095.0,13,0,10286.0,Credit Card,0,2,No,Yes
298,35,Home,574.0,0,1,14745.0,Credit Card,4,1,No,Yes
124,72,Life,2744.0,11,4,4737.0,Bank Transfer,8,1,No,No
185,54,Home,1672.0,11,2,981.0,Bank Transfer,11,1,Yes,Yes

Testing features:

,Age,Policy_Type,Annual_Premium,Years_With_Company,Number_of_Claims,Claim_Amount_Last_Year,Payment_Method,Customer_Service_Calls,Satisfaction_Score,Received_Discount,Auto_Renew_Enabled
259,24,Auto,3129.0,12,1,2261.0,Credit Card,4,4,No,Yes
129,40,Health,4633.0,10,2,11806.0,Bank Transfer,1,4,Yes,Yes
85,71,Life,5801.0,16,3,1334.0,Credit Card,10,3,Yes,No
218,28,Health,2856.0,8,2,806.0,Credit Card,7,3,No,Yes
278,73,Auto,5448.0,0,2,12637.0,Credit Card,7,4,No,Yes

Preprocessing

In [20]:
# Fit the preprocessor only on the training data
X_train_processed = preprocessor.fit_transform(X_train)

# Transform the test data using the same preprocessor
X_test_processed = preprocessor.transform(X_test)

In [21]:
# Display the shape before and after preprocessing

print("Before preprocessing:")
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("\nAfter preprocessing:")
print("X_train_processed:", X_train_processed.shape)
print("X_test_processed:", X_test_processed.shape)

Before preprocessing:
X_train: (272, 11)
X_test: (68, 11)

After preprocessing:
X_train_processed: (272, 18)
X_test_processed: (68, 18)

Train a simple baseline model using Logistic Regression

In [23]:
# Import Logistic Regression from scikit-learn
from sklearn.linear_model import LogisticRegression

In [24]:
# Create a Logistic Regression model
baseline_model = LogisticRegression(max_iter=1000)

In [25]:
# Train the baseline model using the processed training data
# X_train_processed contains the preprocessed features
# y_train contains the correct target labels

baseline_model.fit(X_train_processed, y_train)

LogisticRegression(max_iter=1000)

In [26]:
# Use the trained model to make predictions on the processed test data
y_pred = baseline_model.predict(X_test_processed)

# Display the predicted values
print("Predicted values:")
print(y_pred)

Predicted values:
[1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0
 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1]

In [27]:
# Evaluating the Baseline Model

# Import evaluation metrics from scikit-learn
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import classification_report

In [28]:
# Calculate the accuracy of the baseline model
accuracy = accuracy_score(y_test, y_pred)

# Display the accuracy score
print("Accuracy:", accuracy)

Accuracy: 0.8529411764705882

In [29]:
# Create the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Display the confusion matrix
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[44  3]
 [ 7 14]]

In [30]:
# Display the confusion matrix as a table
cm_table = pd.DataFrame(
    cm,
    index=["Actual No", "Actual Yes"],
    columns=["Predicted No", "Predicted Yes"]
)

cm_table

            Predicted No  Predicted Yes
Actual No             44              3
Actual Yes             7             14

In [31]:
# Calculate precision
# Precision measures how many predicted Yes values were actually Yes
precision = precision_score(y_test, y_pred, zero_division=0)

# Calculate recall
# Recall measures how many actual Yes values were correctly predicted
recall = recall_score(y_test, y_pred, zero_division=0)

# Calculate F1-score
# F1-score balances precision and recall
f1 = f1_score(y_test, y_pred, zero_division=0)

# Display the evaluation results
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Precision: 0.8235294117647058
Recall: 0.6666666666666666
F1-score: 0.7368421052631579

In [32]:
# Display a full classification report
# This includes precision, recall, F1-score, and support for each class

print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=["No", "Yes"], zero_division=0))

Classification Report:
              precision    recall  f1-score   support

          No       0.86      0.94      0.90        47
         Yes       0.82      0.67      0.74        21

    accuracy                           0.85        68
   macro avg       0.84      0.80      0.82        68
weighted avg       0.85      0.85      0.85        68

Interpreting Results

In [33]:
# Display the main evaluation results
print("Baseline Model Results")
print("----------------------")
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Baseline Model Results
----------------------
Accuracy: 0.8529411764705882
Precision: 0.8235294117647058
Recall: 0.6666666666666666
F1-score: 0.7368421052631579

Task 2

In [39]:
# Explanation
print("What your model is trying to predict")
print("The model tries to predict if the customer will renew their insurance policy using logistic regression model.")
print("\nWhat dataset you used")
print("The dataset used is the insurance_policy_renewal_dataset.xls")
print("\nWhat features and target you selected")
print("The features are Age, Policy_Type, Annual_Premium, Years_With_Company, Number_of_Claims," 
      "\nClaim_Amount_Last_Year, Payment_Method, Customer_Service_Calls, Satisfaction_Score,"
      "\nReceived_Discount and Auto_Renew_Enabled, while target is Renewed_Policy.")
print("\nWhat result you obtained")
print("The baseline model achieved an accuracy of 85.29%, precision of 82.35%, recall of 66.67%," 
      "\nand F1-score of 73.68%. These results show that the model performed well in predicting"
      "\ninsurance policy renewals based on the training data provided, although some actual"
      "\nrenewals were still missed by the model.")
print("\nOne limitation of your model or dataset")
print("One limitation of the model is that the recall score is lower than the precision score,"
      "\nwhich means the model missed some customers who actually renewed their insurance policy."
      "\nAnother limitation is that the dataset may not contain all factors / features that"
      "\ninfluence customer renewal decisions.")

What your model is trying to predict
The model tries to predict if the customer will renew their insurance policy using logistic regression model.

What dataset you used
The dataset used is the insurance_policy_renewal_dataset.xls

What features and target you selected
The features are Age, Policy_Type, Annual_Premium, Years_With_Company, Number_of_Claims,
Claim_Amount_Last_Year, Payment_Method, Customer_Service_Calls, Satisfaction_Score,
Received_Discount and Auto_Renew_Enabled, while target is Renewed_Policy.

What result you obtained
The baseline model achieved an accuracy of 85.29%, precision of 82.35%, recall of 66.67%,
and F1-score of 73.68%. These results show that the model performed well in predicting
insurance policy renewals based on the training data provided, although some actual
renewals were still missed by the model.

One limitation of your model or dataset
One limitation of the model is that the recall score is lower than the precision score,
which means the model missed some customers who actually renewed their insurance policy.
Another limitation is that the dataset may not contain all factors / features that
influence customer renewal decisions.